### ISSUE TITLE
build using musl libc 

### ISSUE THREAD

**Issue by ScrumpyJack** [jjguti/hermes#1]
hi. I'm building hermes using musl libc and I'm getting the following error

```
Utils.cpp: In static member function 'static std::__cxx11::string Utils::errnotostrerror(int)':
Utils.cpp:423:20: error: invalid conversion from 'int' to 'char*' [-fpermissive] strerr=strerror_r(errnum,buf,2048);
```

would you be kind enough to take a look at this?

**Comment by jjguti** [comment]
Hi, it seems like the strerror_r which hermes was using is only available with glibc. I have ifdef it so that it should be possible to build now with other libc's such as musl. Please try again and report if it works

**Comment by ScrumpyJack** [comment]
Yes, that builds fine now, thank you very much!
